# Generated by Django 3.2.9 on 2021-11-02 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.TextField()),
                ('maxUserNumber', models.SmallIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('BUILD_REQUIRED', 'Build required'), ('BUILDING', 'Building'), ('BUILT', 'Built'), ('STOP_REQUIRED', 'Stop required'), ('STOPPING', 'Stopping'), ('STOPED', 'Stoped'), ('RUNNING_REQUIRED', 'Running required'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('UNKNOWN', 'Unknown')], default='BUILD_REQUIRED', max_length=20)),
                ('docker_id', models.TextField(blank=True, max_length=100, unique=True)),
                ('domain_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect domain_name', regex='^((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\\.(xn--)?([a-z0-9\\-]{1,61}|[a-z0-9-]{1,30}\\.[a-z]{2,})$')])),
                ('password', models.TextField(default='admin', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
