# Generated by Django 3.2.9 on 2022-01-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_server_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
